data_dir = 'data/'
dynaboard_model_outputs = 'dynaboard_model_outputs'
tasks = ["hs", "nli", "qa", "sentiment"]

[sentiment_names.dev]
amazon = "amazon-review-dev"
dynasent_r1 = "dynasent-r1-dev"
dynasent_r2 = "dynasent-r2-dev"
sst3 = "sst3-dev"
yelp = "yelp-review-dev"

[reviews.dev]
amazon = "datasets/sentiment/amazon-review-dev.jsonl"
dynasent_r1 = "datasets/sentiment/dynasent-r1-dev.jsonl"
dynasent_r2 = "datasets/sentiment/dynasent-r2-dev.jsonl"
sst3 = "datasets/sentiment/sst3-dev.jsonl"
yelp = "datasets/sentiment/yelp-review-dev.jsonl"

[mallet_reviews.dev]
amazon = "datasets/sentiment/amazon-review-dev.mallet"
dynasent_r1 = "datasets/sentiment/dynasent-r1-dev.mallet"
dynasent_r2 = "datasets/sentiment/dynasent-r2-dev.mallet"
sst3 = "datasets/sentiment/sst3-dev.mallet"
yelp = "datasets/sentiment/yelp-review-dev.mallet"

[topic."num_topics=10"]
num_topics = 10
output_dir = "topic-model/sentiment/num_topics=10"
